package com.event.anime.model.item

import com.squareup.moshi.Json

data class Anime(
    @Json(name = "mal_id") val malId: Int? = null,
    @Json(name = "url") val url: String? = null,
    @Json(name = "images") val images: Images? = null,
    @Json(name = "trailer") val trailer: Trailer? = null,
    @Json(name = "approved") val approved: Boolean? = null,
    @Json(name = "titles") val titles: List<Title>? = null,
    @Json(name = "title") val title: String? = null,
    @Json(name = "title_english") val titleEnglish: String? = null,
    @Json(name = "title_japanese") val titleJapanese: String? = null,
    @Json(name = "title_synonyms") val titleSynonyms: List<String>? = null,
    @Json(name = "type") val type: String? = null,
    @Json(name = "source") val source: String? = null,
    @Json(name = "episodes") val episodes: Int? = null,
    @Json(name = "status") val status: String? = null,
    @Json(name = "airing") val airing: Boolean? = null,
    @Json(name = "aired") val aired: Aired? = null,
    @Json(name = "duration") val duration: String? = null,
    @Json(name = "rating") val rating: String? = null,
    @Json(name = "score") val score: Double? = null,
    @Json(name = "scored_by") val scoredBy: Long? = null,
    @Json(name = "rank") val rank: Int? = null,
    @Json(name = "popularity") val popularity: Long? = null,
    @Json(name = "members") val members: Long? = null,
    @Json(name = "favorites") val favorites: Long? = null,
    @Json(name = "synopsis") val synopsis: String? = null,
    @Json(name = "background") val background: String? = null,
    @Json(name = "season") val season: String? = null,
    @Json(name = "year") val year: Int? = null,
    @Json(name = "broadcast") val broadcast: Broadcast? = null,
    @Json(name = "producers") val producers: List<Data>? = null,
    @Json(name = "licensors") val licensors: List<Data>? = null,
    @Json(name = "studios") val studios: List<Data>? = null,
    @Json(name = "genres") val genres: List<Data>? = null,
    @Json(name = "explicit_genres") val explicitGenres: List<Data>? = null,
    @Json(name = "themes") val themes: List<Data>? = null,
    @Json(name = "demographics") val demographics: List<Data>? = null,
)
